### ISSUE TITLE
USER STORY: Approve reservations

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#10]
As a **site admin** I can **approve/disapprove reservations** so that **to make sure that there is enough room for the guests**

## Acceptance Criteria
* When I **get a reservation request** This happens **I can approve /disapprove it**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - create template to render the view
- [x] Task 3 - Connect up URL's
