### ISSUE TITLE
USER STORY: Make a reservation

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#11]
As a **User** I can **Create, edit and delete a reservation** so that **I can manage the reservation**

## Acceptance Criteria
* When I **Create a reservation** This happens **I can come back to edit and delete the reservation if I can't attend**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - Create template to render the view
- [x] Task 3 - Connect the URL's
