### ISSUE TITLE
USER STORY: Contact cafe

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#17]
As a **User** I can **Contact the cafe via email** so that ***I can get any questions answered*

## Acceptance Criteria
* When I **Send a contact message** This happens **I receive a message to confirm my message was sent**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - Create template to render the view
- [x] Task 3 - Connect the urls and api for message sending
