### ISSUE TITLE
USER STORY: Cafe Location

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#18]
As a **User** I can **See the location of the cafe** so that **I know how to get there**

## Acceptance Criteria
* When I **Land on the contact us page ** This happens **I can see the location of the cafe on a map**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - Create template to render the view
- [x] Task 3 - Connect the api for maps and URL's
