### ISSUE TITLE
USER STORY: Receive contact

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#19]
As a **site admin** I can **be notified of a message being received** so that **I can respond promptly**

## Acceptance Criteria
* When I **get sent a message** This happens **I receive a notification email**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - Create template to render view
- [x] Task 3 - Connect message api and URL's
