### ISSUE TITLE
USER STORY: Site Registration

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#2]
As a **new user** I can **Easily register for the site** so that **I can interact with the site content**

## Acceptance Criteria
* When I **Register for the site** This happens **I am notified that I am logged in and can interact with the site content**

## Tasks
- [x] Task 1 - Create user model
- [x] Task 2 - Wire up urls
- [x] Task 3 - Create HTML and CSS
