### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#21]
As a **user** I can **intuitively understand the site and meaning** so that **I know if I want to stay on the site**

## Acceptance Criteria
* When I **land on the site** This happens **I understand the purpose of the site**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - Create template to render the view
- [x] Task 3 - Connect the urls
