### ISSUE TITLE
USER STORY: Site navigation

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#22]
As a **user** I can **intuitively navigate the site** so that **I can register/ login and make a reservation**

## Acceptance Criteria
* When I **see the navigation bar I know where it is going to take me** This happens **I am navigated the the page of my choice**

## Tasks
- [x] Task 1 - Create base navigation template
- [x] Task 2 - Create Html and css
- [x] Task 3 - Connect page urls
