### ISSUE TITLE
USER STORY: View socials

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#23]
As a **user** I can **Follow the sites social networks** so that ** I can see events and offers**

## Acceptance Criteria
* When I **view the page footer I can click on the social account** This happens **I get a new tab open with the cafe's social pages**

## Tasks
- [x] Task 1 - Create base template
- [x] Task 2 - Create Html and css
- [x] Task 3 - Connect urls
