### ISSUE TITLE
USER STORY: Edit Delete menu items

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#6]
As a **site admin** I can **Edit/ Delete items on the menu** so that **Keep the menu up to date**

## Acceptance Criteria
* When I **update/edit or delete a menu item** This happens **it is updated accordingly on the site**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - Create template to render the view
- [x] Task 3 - connect URL's
