### ISSUE TITLE
USER STORY: Like/Unlike menu Items

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#7]
As a **site admin.user** I can **see the number of likes a menu item has** so that **I can see how popular it is**

## Acceptance Criteria
* When I **like a menu item I can like/unlike it** This happens **I can see how popular a menu item is**

## Tasks
- [x] Task 1 - Create view code
- [x] Task 2 - Create template to render the view
- [x] Task 3 - Connect up the URL's
