### ISSUE TITLE
USER STORY:  Daily Reservations

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/cockapoo-cafe#9]
As a **site admin** I can **Create, edit and delete reservation time slots for customers to select** so that **rthe reservations are with in the shop opening hours**

## Acceptance Criteria
* When I **create a reservation time slot** This happens **it is able to be selected by a user**

## Tasks
- [ ] Task 1 - Create view code
- [ ] Task 2 - Create template to render the view
- [ ] Task 3 - Connect up URL's

**Comment by Steven-Dawson18** [comment]
As I have progressed through creating the site, this User story does not seen relevant. The reason I believe that it is not relevant is that I am yet to see a cafe extend it's opening times. In fact the best businesses are the ones who have regular opening times so customers know exactly when they can go. For this reason I am not going to implement this user story.
